### ISSUE TITLE
Feature request: allow specifying mainline

### ISSUE THREAD

**Issue by houserx-jmcc** [korthout/backport-action#341]
Allow specifying a default [mainline](https://git-scm.com/docs/git-cherry-pick#Documentation/git-cherry-pick.txt--mltparent-numbergt) to use when cherry picking and if supplied use it, i.e. `git cherry-pick 1234567 -m 1`. Since this action can be used in very specific workflows (like my use case!), this could be a useful option to specify.

Example:

```yaml
steps:
      - uses: actions/checkout@v3
      - name: Create backport pull requests
        uses: korthout/backport-action@v1
        with:
           default_mainline: 1
```
