### ISSUE TITLE
Feature request : backport to all open feature branches

### ISSUE THREAD

**Issue by RupertBarrow** [korthout/backport-action#343]
It would be nice to be able to backport to all feature branches currently open named eg 'feature/*'.
The configuration would be something like:
- from: main
- to: feature/*
for example.

This would create a PR on each feature/* branch.

**Comment by korthout** [comment]
Hi @RupertBarrow 👋 That's a great request!

✅ You can use the [`target_branches`](https://github.com/korthout/backport-action#target_branches) input for this, since [`v1.3.0`](https://github.com/korthout/backport-action/releases/tag/v1.3.0).

**Note** that the `target_branches` input requires space-delimited branches, so finding these requires an extra step in your workflow.

```yml Example workflow
name: Backport to all feature branches
on:
  pull_request_target:
    types: [closed]
permissions:
  contents: write # so it can comment
  pull-requests: write # so it can create pull requests
jobs:
  backport:
    name: Open backport pull requests
    runs-on: ubuntu-latest
    # Don't run on closed unmerged pull requests
    if: github.event.pull_request.merged
    steps:
      - uses: actions/checkout@v3
        with:
          # Fetch all branches
          fetch-depth: 0
      
      - id: branches
        shell: bash
        # list all banches, filtering for 'feature/*', and cutting off remotes/origin/
        # then finally substitute newlines for spaces
        run: |
          branches=$(git branch --list --all | grep 'origin/feature/' | cut -c 18- )
          space_delimited=${branches//$'\n'/ }
          echo "BRANCHES=${space_delimited}" >> $GITHUB_OUTPUT
      
      - uses: korthout/backport-action@v1
        with:
          # now you can use the branches output in the backport-action
          target_branches: ${{ steps.branches.outputs.BRANCHES }}
```

<details><summary>Tested with an example workflow</summary>
<p>

[Example run](https://github.com/korthout/zeebe/actions/runs/5134971757/jobs/9239736633), using workflow:

```yml
name: Space delimit branches
on:
  workflow_dispatch: {}
jobs:
  branches:
    name: Space delimited branches
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: branches
        shell: bash
        run: |
          branches=$(git branch --list --all | grep 'origin/stable/' | cut -c 18- )
          space_delimited=${branches//$'\n'/ }
          echo "BRANCHES=${space_delimited}" >> $GITHUB_OUTPUT
      - run: echo "${{ steps.branches.outputs.BRANCHES }}"
```

</p>
</details>
