### ISSUE TITLE
Support glob patterns in `target_branches` input

### ISSUE THREAD

**Issue by korthout** [korthout/backport-action#349]
Some users want to automatically backport a pull request to a dynamically defined set of target branches.

For example, in https://github.com/korthout/backport-action/issues/343 the request was to backport to all branches matching the `feature/*` pattern.

A workaround is available by adding an additional step in the workflow to expand the pattern into the branch refs:

```yml
- uses: actions/checkout@v3
  with:
    # Fetch all branches
    fetch-depth: 0
- id: branches
  shell: bash
  # list all banches, filtering for 'feature/*', and cutting off remotes/origin/
  # then finally substitute newlines for spaces
  run: |
    branches=$(git branch --list --all | grep 'origin/feature/' | cut -c 18- )
    space_delimited=${branches//$'\n'/ }
    echo "BRANCHES=${space_delimited}" >> $GITHUB_OUTPUT
- uses: korthout/backport-action@v1
  with:
    # now you can use the branches output in the backport-action
    target_branches: ${{ steps.branches.outputs.BRANCHES }}
```

However, it would be great to support this directly in the `target_branches` input as:

```yml
- uses: actions/checkout@v3
  with:
    # Fetch all branches
    fetch-depth: 0
- uses: korthout/backport-action@v1
  with:
    target_branches: 'feature/*'
```

> **Note** that a deep checkout (`fetch-depth:0`) is required to fetch all branches.
